spring:
  profiles:
    active: prod
    
security:
  jwt:
    secret: ${JWT_SECRET}  # Must be set via environment variable
    expiration: 3600
    refresh-expiration: 86400
    
  cors:
    allowed-origins:
      - https://hunting.yourdomain.com
      - https://hunting-admin.yourdomain.com
    max-age: 3600

server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/ssl/hunting-system/keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: hunting-system
    protocol: TLS
    enabled-protocols: TLSv1.3,TLSv1.2
    
management:
  server:
    port: 8444
    ssl:
      enabled: true

logging:
  level:
    com.hunting: INFO
    org.springframework.security: WARN
    org.springframework.web.cors: WARN
    root: WARN
  file:
    name: /var/log/hunting-system/security.log