package com.ops.hunting.threatintel.entity;

public enum ArtifactType {
	IOC, INTELLIGENCE, EVENT, ALERT, MALWARE_SAMPLE, NETWORK_TRAFFIC, PROCESS_DATA, FILE_HASH, REGISTRY_KEY, DOMAIN,
	IP_ADDRESS, URL, EMAIL, CERTIFICATE, RULE, SIGNATURE, YARA_RULE, SIGMA_RULE
}
