server:
  port: 8082

spring:
  application:
    name: threat-intelligence-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/persistent_hunt_system
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: ${ELASTICSEARCH_USERNAME:}
      password: ${ELASTICSEARCH_PASSWORD:}
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  cache:
    type: redis
    redis:
      time-to-live: 600000
      
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: threat-intelligence-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.persistenthunt.*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.persistenthunt.threatintel: DEBUG
    org.springframework.data.elasticsearch: DEBUG
