server:
  port: 8084

spring:
  application:
    name: alert-management-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/persistent_hunt_system
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  cache:
    type: redis
    redis:
      time-to-live: 300000
      
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: alert-management-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.persistenthunt.*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.persistenthunt.alerts: DEBUG

# Alert configuration
alert:
  auto-escalation:
    enabled: true
    critical-threshold-minutes: 15
    high-threshold-minutes: 60
  notifications:
    enabled: true
    webhook-url: http://localhost:8080/webhooks/alerts